# ==============================================================
# = Authentication Server JWT
# ==============================================================
spring:
    application:
        name: AUTH-SERVICE
server:
    port: 9100

# ==============================================================
# = Parametri Servizio gestUser
# ==============================================================
getuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: Admin
  password: springBoot

# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 3600
    secret: $spring@david.it

# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org.springframework.security: DEBUG
##usiamo debug per avere più informazioni a livello di servizio

        

  
 