#========================================================
#= GetUser Web Service - Versione Base
#========================================================

server:
  port: 8019
spring:
  application:
   name: GetUser
   
#========================================================
#= PARAMETRI DB MONGODB
#========================================================
       
  data:
    mongodb:
      authentication-database: admin
      database: ms-users
      host: localhost
      password: java
      port: 37017
      username: mirko
      auto-index-creation: true
